[features]
seeds = false
skip-lint = false
[programs.localnet]
wsos23_voting_app = "DAExTRo6cEotQAgtREjCrS6R2tL54VfgBWsP7xozMiht"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
